_extends: policies:release-drafter.yml
name-template: "ControllerMissingKubernetesAppPartOfLabel/v$RESOLVED_VERSION"
tag-template: "ControllerMissingKubernetesAppPartOfLabel/v$RESOLVED_VERSION"
tag-prefix: ControllerMissingKubernetesAppPartOfLabel/v
include-paths:
  - "policies/ControllerMissingKubernetesAppPartOfLabel/"
