_extends: policies:release-drafter.yml
name-template: "FluxGitRepositorySpecificBranch/v$RESOLVED_VERSION"
tag-template: "FluxGitRepositorySpecificBranch/v$RESOLVED_VERSION"
tag-prefix: FluxGitRepositorySpecificBranch/v
include-paths:
  - "policies/FluxGitRepositorySpecificBranch/"
