_extends: policies:release-drafter.yml
name-template: "FluxHelmReleaseRemediationRetries/v$RESOLVED_VERSION"
tag-template: "FluxHelmReleaseRemediationRetries/v$RESOLVED_VERSION"
tag-prefix: FluxHelmReleaseRemediationRetries/v
include-paths:
  - "policies/FluxHelmReleaseRemediationRetries/"
