_extends: policies:release-drafter.yml
name-template: "RBACProhibitWildcardOnSecrets/v$RESOLVED_VERSION"
tag-template: "RBACProhibitWildcardOnSecrets/v$RESOLVED_VERSION"
tag-prefix: RBACProhibitWildcardOnSecrets/v
include-paths:
  - "policies/RBACProhibitWildcardOnSecrets/"
