_extends: policies:release-drafter.yml
name-template: "NamespaceLimitRangeMinMax/v$RESOLVED_VERSION"
tag-template: "NamespaceLimitRangeMinMax/v$RESOLVED_VERSION"
tag-prefix: NamespaceLimitRangeMinMax/v
include-paths:
  - "policies/NamespaceLimitRangeMinMax/"
