_extends: policies:release-drafter.yml
name-template: "RBACProhibitWildcardsOnPolicyRuleResources/v$RESOLVED_VERSION"
tag-template: "RBACProhibitWildcardsOnPolicyRuleResources/v$RESOLVED_VERSION"
tag-prefix: RBACProhibitWildcardsOnPolicyRuleResources/v
include-paths:
  - "policies/RBACProhibitWildcardsOnPolicyRuleResources/"
