_extends: policies:release-drafter.yml
name-template: "FluxKustomizationTargetNamespace/v$RESOLVED_VERSION"
tag-template: "FluxKustomizationTargetNamespace/v$RESOLVED_VERSION"
tag-prefix: FluxKustomizationTargetNamespace/v
include-paths:
  - "policies/FluxKustomizationTargetNamespace/"
