_extends: policies:release-drafter.yml
name-template: "FluxGitRepositoryUntrustedDomains/v$RESOLVED_VERSION"
tag-template: "FluxGitRepositoryUntrustedDomains/v$RESOLVED_VERSION"
tag-prefix: FluxGitRepositoryUntrustedDomains/v
include-paths:
  - "policies/FluxGitRepositoryUntrustedDomains/"
