_extends: policies:release-drafter.yml
name-template: "IstioGatewayHosts/v$RESOLVED_VERSION"
tag-template: "IstioGatewayHosts/v$RESOLVED_VERSION"
tag-prefix: IstioGatewayHosts/v
include-paths:
  - "policies/IstioGatewayHosts/"
