_extends: policies:release-drafter.yml
name-template: "NamespacePodQuota/v$RESOLVED_VERSION"
tag-template: "NamespacePodQuota/v$RESOLVED_VERSION"
tag-prefix: NamespacePodQuota/v
include-paths:
  - "policies/NamespacePodQuota/"
