_extends: policies:release-drafter.yml
name-template: "RBACProhibitWatchOnSecrets/v$RESOLVED_VERSION"
tag-template: "RBACProhibitWatchOnSecrets/v$RESOLVED_VERSION"
tag-prefix: RBACProhibitWatchOnSecrets/v
include-paths:
  - "policies/RBACProhibitWatchOnSecrets/"
