_extends: policies:release-drafter.yml
name-template: "NetworkPolicyAllowEgressFromNamespaceToNamespace/v$RESOLVED_VERSION"
tag-template: "NetworkPolicyAllowEgressFromNamespaceToNamespace/v$RESOLVED_VERSION"
tag-prefix: NetworkPolicyAllowEgressFromNamespaceToNamespace/v
include-paths:
  - "policies/NetworkPolicyAllowEgressFromNamespaceToNamespace/"
