_extends: policies:release-drafter.yml
name-template: "ControllerContainerBlockSSHPort/v$RESOLVED_VERSION"
tag-template: "ControllerContainerBlockSSHPort/v$RESOLVED_VERSION"
tag-prefix: ControllerContainerBlockSSHPort/v
include-paths:
  - "policies/ControllerContainerBlockSSHPort/"
