_extends: policies:release-drafter.yml
name-template: "RBACProhibitListOnSecrets/v$RESOLVED_VERSION"
tag-template: "RBACProhibitListOnSecrets/v$RESOLVED_VERSION"
tag-prefix: RBACProhibitListOnSecrets/v
include-paths:
  - "policies/RBACProhibitListOnSecrets/"
