_extends: policies:release-drafter.yml
name-template: "NetworkPolicyBlockIngressAllToNamespaceFromCIDR/v$RESOLVED_VERSION"
tag-template: "NetworkPolicyBlockIngressAllToNamespaceFromCIDR/v$RESOLVED_VERSION"
tag-prefix: NetworkPolicyBlockIngressAllToNamespaceFromCIDR/v
include-paths:
  - "policies/NetworkPolicyBlockIngressAllToNamespaceFromCIDR/"
