_extends: policies:release-drafter.yml
name-template: "ControllerMissingKubernetesAppCreatedByLabel/v$RESOLVED_VERSION"
tag-template: "ControllerMissingKubernetesAppCreatedByLabel/v$RESOLVED_VERSION"
tag-prefix: ControllerMissingKubernetesAppCreatedByLabel/v
include-paths:
  - "policies/ControllerMissingKubernetesAppCreatedByLabel/"
