_extends: policies:release-drafter.yml
name-template: "FluxHelmReleaseServiceAccountName/v$RESOLVED_VERSION"
tag-template: "FluxHelmReleaseServiceAccountName/v$RESOLVED_VERSION"
tag-prefix: FluxHelmReleaseServiceAccountName/v
include-paths:
  - "policies/FluxHelmReleaseServiceAccountName/"
