_extends: policies:release-drafter.yml
name-template: "ControllerMissingLabelValue/v$RESOLVED_VERSION"
tag-template: "ControllerMissingLabelValue/v$RESOLVED_VERSION"
tag-prefix: ControllerMissingLabelValue/v
include-paths:
  - "policies/ControllerMissingLabelValue/"
