[package]
name = "raw-validation-policy"
version = "0.1.0"
authors = ["Fabrizio Sestito <fabrizio.sestito@suse.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
kubewarden-policy-sdk = { workspace = true }
k8s-openapi = { workspace = true }                  # consume feature from workspace crate
lazy_static = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
slog = { workspace = true }
