rules:
  - apiGroups: [helm.toolkit.fluxcd.io]
    apiVersions: [v2]
    resources: [helmreleases]
    operations: [CREATE, UPDATE]
mutating: false
executionMode: gatekeeper
backgroundAudit: true
annotations:
  io.artifacthub.displayName: Helm Release Values From
  io.artifacthub.keywords: flux
  io.artifacthub.resources: HelmRelease
  io.kubewarden.policy.title: helm-release-values-from-configmaps
  io.kubewarden.policy.version: 1.0.4
  io.kubewarden.policy.description: "HelmRelease valuesFrom must use correctly configured ConfigMaps."
  io.kubewarden.policy.author: Kubewarden developers <cncf-kubewarden-maintainers@lists.cncf.io>
  io.kubewarden.policy.ociUrl: ghcr.io/kubewarden/policies/helm-release-values-from-configmaps
  io.kubewarden.policy.url: https://github.com/kubewarden/policies
  io.kubewarden.policy.source: https://github.com/kubewarden/policies
  io.kubewarden.policy.license: Apache-2.0
  io.kubewarden.policy.category: best-practices
  io.kubewarden.policy.severity: medium
